import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider.jsx";
import Navbar from "./components/Navbar/Navbar";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.variable} flex flex-col h-screen`}>
        <Navbar />
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
